CREATE TABLE MFA_ACCOUNTS (
     ID INT CHECK (ID > 0) NOT NULL AUTO_INCREMENT,
     ACCOUNT_NAME VARCHAR(50) NOT NULL,
     USERPASSWORD VARCHAR(100) NOT NULL,
     ISENCRYPTED VARCHAR(10) NOT NULL,
     PRIMARY KEY(ID, ACCOUNT_NAME, USERPASSWORD)
);

CREATE TABLE MFA_VALIDATION_ATTEMPTS (
    ID INT CHECK (ID > 0) NOT NULL AUTO_INCREMENT,
    ACCESS_TIME DATETIME NOT NULL,
    CTS CLOB NOT NULL,
    ACCOUNT_NAME VARCHAR(50) NOT NULL,
    SUCCEEDED TINYINT NOT NULL,
    PRIMARY KEY(ID)
);